/**
 * F-015 built-in spec templates.
 * Five immutable starter packs shipped as extension resources.
 * Placeholders: {{title}} and {{date}} are expanded at creation time.
 */

import type { SpecTemplate } from "./templateTypes"

export const BUILTIN_TEMPLATES: ReadonlyArray<SpecTemplate> = [
	{
		id: "requirements",
		name: "Requirements",
		description: "Capture functional and non-functional requirements for a feature.",
		version: 1,
		source: "builtin",
		documents: [
			{
				id: "requirements",
				kind: "requirements",
				title: "Requirements",
				fileName: "requirements.md",
				content: [
					"# Requirements — {{title}}",
					"",
					"## Functional Requirements",
					"",
					"_TODO: list functional requirements._",
					"",
					"## Non-Functional Requirements",
					"",
					"_TODO: list non-functional requirements (performance, security, etc.)._",
					"",
					"## Acceptance Criteria",
					"",
					"_TODO: define measurable acceptance criteria._",
					"",
				].join("\n"),
			},
		],
	},
	{
		id: "architecture-design",
		name: "Architecture Design",
		description: "Document system architecture, components, and data flow.",
		version: 1,
		source: "builtin",
		documents: [
			{
				id: "design",
				kind: "design",
				title: "Architecture Design",
				fileName: "design.md",
				content: [
					"# Architecture Design — {{title}}",
					"",
					"## Overview",
					"",
					"_TODO: describe the high-level architecture._",
					"",
					"## Components",
					"",
					"_TODO: list key components and their responsibilities._",
					"",
					"## Data Flow",
					"",
					"_TODO: describe how data moves through the system._",
					"",
					"## Trade-offs",
					"",
					"_TODO: document architectural trade-offs._",
					"",
				].join("\n"),
			},
		],
	},
	{
		id: "api-design",
		name: "API Design",
		description: "Define API endpoints, request/response schemas, and error handling.",
		version: 1,
		source: "builtin",
		documents: [
			{
				id: "design",
				kind: "design",
				title: "API Design",
				fileName: "design.md",
				content: [
					"# API Design — {{title}}",
					"",
					"## Endpoints",
					"",
					"_TODO: list API endpoints with methods and paths._",
					"",
					"## Request/Response Schemas",
					"",
					"_TODO: define request and response shapes._",
					"",
					"## Error Handling",
					"",
					"_TODO: describe error codes and responses._",
					"",
				].join("\n"),
			},
			{
				id: "requirements",
				kind: "requirements",
				title: "API Requirements",
				fileName: "requirements.md",
				content: [
					"# API Requirements — {{title}}",
					"",
					"## Functional Requirements",
					"",
					"_TODO: list API-specific requirements._",
					"",
				].join("\n"),
			},
		],
	},
	{
		id: "adr",
		name: "ADR",
		description: "Architecture Decision Record for documenting a single decision.",
		version: 1,
		source: "builtin",
		documents: [
			{
				id: "notes",
				kind: "notes",
				title: "ADR",
				fileName: "notes.md",
				content: [
					"# ADR — {{title}}",
					"",
					"**Date:** {{date}}",
					"",
					"## Status",
					"",
					"_Proposed_",
					"",
					"## Context",
					"",
					"_TODO: describe the context and problem._",
					"",
					"## Decision",
					"",
					"_TODO: describe the decision made._",
					"",
					"## Consequences",
					"",
					"_TODO: describe the consequences (positive and negative)._",
					"",
				].join("\n"),
			},
		],
	},
	{
		id: "implementation-plan",
		name: "Implementation Plan",
		description: "Break down implementation into tasks and track progress.",
		version: 1,
		source: "builtin",
		documents: [
			{
				id: "requirements",
				kind: "requirements",
				title: "Requirements Summary",
				fileName: "requirements.md",
				content: [
					"# Requirements Summary — {{title}}",
					"",
					"_TODO: summarize the requirements for this implementation._",
					"",
				].join("\n"),
			},
			{
				id: "design",
				kind: "design",
				title: "Design Summary",
				fileName: "design.md",
				content: [
					"# Design Summary — {{title}}",
					"",
					"_TODO: summarize the design for this implementation._",
					"",
				].join("\n"),
			},
			{
				id: "tasks",
				kind: "tasks",
				title: "Implementation Tasks",
				fileName: "tasks.md",
				content: [
					"# Implementation Tasks — {{title}}",
					"",
					"- [ ] Task 1",
					"- [ ] Task 2",
					"- [ ] Task 3",
					"",
				].join("\n"),
			},
		],
	},
] as const
