import { createHash } from "crypto"
import * as path from "path"

import type { SpecDocKind, SpecStage } from "../types"
import {
	SPEC_PACKAGE_FORMAT,
	SPEC_PACKAGE_VERSION,
	type SpecPackage,
	type SpecPackageDocument,
} from "./specPackageTypes"

export const MAX_SPEC_PACKAGE_BYTES = 12 * 1024 * 1024
export const MAX_SPEC_PACKAGE_DOCUMENTS = 50
export const MAX_SPEC_PACKAGE_DOCUMENT_BYTES = 1024 * 1024

const SPEC_STAGES = new Set<SpecStage>(["requirements", "design", "tasks"])
const SPEC_DOC_KINDS = new Set<SpecDocKind>(["requirements", "design", "tasks", "notes", "custom"])

export function hashSpecPackageContent(content: string): string {
	return createHash("sha256").update(content, "utf8").digest("hex")
}

/**
 * Stable JSON representation used for packageHash. Defensively strips any
 * pre-existing `packageHash` so that passing a full {@link SpecPackage}
 * (e.g. a re-serialized plan package) never leaks a stale hash into the
 * canonical payload and produces a self-inconsistent packageHash.
 */
export function canonicalSpecPackagePayload(pkg: Omit<SpecPackage, "packageHash">): string {
	const { packageHash: _ignored, ...payload } = pkg as SpecPackage
	return JSON.stringify(payload)
}

export function computeSpecPackageHash(pkg: Omit<SpecPackage, "packageHash">): string {
	return hashSpecPackageContent(canonicalSpecPackagePayload(pkg))
}

export function serializeSpecPackage(pkg: Omit<SpecPackage, "packageHash">): string {
	const complete: SpecPackage = {
		...pkg,
		packageHash: computeSpecPackageHash(pkg),
	}
	return `${JSON.stringify(complete, null, 2)}\n`
}

export function parseSpecPackage(raw: string): SpecPackage {
	if (Buffer.byteLength(raw, "utf8") > MAX_SPEC_PACKAGE_BYTES) {
		throw new Error(`Spec package exceeds ${MAX_SPEC_PACKAGE_BYTES} byte limit`)
	}

	let value: unknown
	try {
		value = JSON.parse(raw)
	} catch (error) {
		throw new Error(`Invalid .zspec JSON: ${error instanceof Error ? error.message : String(error)}`)
	}
	if (!isRecord(value)) throw new Error("Invalid .zspec package: root must be an object")
	if (value.format !== SPEC_PACKAGE_FORMAT) {
		throw new Error(`Invalid .zspec format: expected ${SPEC_PACKAGE_FORMAT}`)
	}
	if (value.formatVersion !== SPEC_PACKAGE_VERSION) {
		throw new Error(`Unsupported .zspec formatVersion: ${String(value.formatVersion)}`)
	}
	if (!isFiniteTimestamp(value.exportedAt)) throw new Error("Invalid .zspec exportedAt")
	if (typeof value.exporter !== "string" || !value.exporter.trim()) {
		throw new Error("Invalid .zspec exporter")
	}
	if (!isRecord(value.source)) throw new Error("Invalid .zspec source metadata")
	const source = value.source
	if (typeof source.title !== "string" || !source.title.trim()) {
		throw new Error("Invalid .zspec source title")
	}
	if (!SPEC_STAGES.has(source.stage as SpecStage)) throw new Error("Invalid .zspec source stage")
	if (!isFiniteTimestamp(source.createdAt) || !isFiniteTimestamp(source.updatedAt)) {
		throw new Error("Invalid .zspec source timestamps")
	}
	if (!Number.isInteger(source.schemaVersion) || Number(source.schemaVersion) < 1) {
		throw new Error("Invalid .zspec source schemaVersion")
	}
	if (!Array.isArray(value.documents) || value.documents.length === 0) {
		throw new Error("Invalid .zspec package: at least one document is required")
	}
	if (value.documents.length > MAX_SPEC_PACKAGE_DOCUMENTS) {
		throw new Error(`Spec package exceeds ${MAX_SPEC_PACKAGE_DOCUMENTS} document limit`)
	}

	const seenIds = new Set<string>()
	const seenFiles = new Set<string>()
	const documents = value.documents.map((entry, index) => validateDocument(entry, index, seenIds, seenFiles))

	const pkg: SpecPackage = {
		format: SPEC_PACKAGE_FORMAT,
		formatVersion: SPEC_PACKAGE_VERSION,
		exportedAt: value.exportedAt as number,
		exporter: value.exporter.trim(),
		source: {
			specId: typeof source.specId === "string" && source.specId.trim() ? source.specId.trim() : undefined,
			title: source.title.trim(),
			stage: source.stage as SpecStage,
			createdAt: source.createdAt as number,
			updatedAt: source.updatedAt as number,
			schemaVersion: source.schemaVersion as number,
		},
		documents,
		packageHash: typeof value.packageHash === "string" ? value.packageHash : undefined,
	}

	if (pkg.packageHash) {
		const { packageHash: _ignored, ...payload } = pkg
		const current = computeSpecPackageHash(payload)
		if (current !== pkg.packageHash) throw new Error("Spec package hash mismatch")
	}
	return pkg
}

/**
 * Map package kinds to current storage kinds. Future/unknown kinds remain
 * importable as custom, with a collision-safe id generated by the coordinator.
 */
export function normalizeImportedDocumentKind(kind: string): SpecDocKind {
	return SPEC_DOC_KINDS.has(kind as SpecDocKind) ? (kind as SpecDocKind) : "custom"
}

export function safePackageDocumentFileName(fileName: string, kind: SpecDocKind, id: string): string {
	const candidate = path.basename(fileName.replace(/\\/g, "/"))
	if (
		candidate &&
		candidate === fileName.replace(/\\/g, "/").split("/").pop() &&
		/^[a-zA-Z0-9._-]+\.md$/i.test(candidate) &&
		!candidate.includes("..")
	) {
		return candidate
	}
	const safeId = id.replace(/[^a-zA-Z0-9_-]/g, "-").replace(/^-+|-+$/g, "") || kind
	return `${safeId}.md`
}

function validateDocument(
	value: unknown,
	index: number,
	seenIds: Set<string>,
	seenFiles: Set<string>,
): SpecPackageDocument {
	if (!isRecord(value)) throw new Error(`Invalid .zspec document at index ${index}`)
	const id = requireText(value.id, `documents[${index}].id`)
	const kind = requireText(value.kind, `documents[${index}].kind`)
	const title = requireText(value.title, `documents[${index}].title`)
	const fileName = requireText(value.fileName, `documents[${index}].fileName`)
	if (seenIds.has(id)) throw new Error(`Duplicate .zspec document id: ${id}`)
	seenIds.add(id)
	const foldedFile = fileName.toLowerCase()
	if (seenFiles.has(foldedFile)) throw new Error(`Duplicate .zspec document fileName: ${fileName}`)
	seenFiles.add(foldedFile)
	if (!Number.isInteger(value.revision) || Number(value.revision) < 1) {
		throw new Error(`Invalid .zspec revision for ${id}`)
	}
	if (!isFiniteTimestamp(value.createdAt) || !isFiniteTimestamp(value.updatedAt)) {
		throw new Error(`Invalid .zspec timestamps for ${id}`)
	}
	if (typeof value.content !== "string") throw new Error(`Invalid .zspec content for ${id}`)
	if (Buffer.byteLength(value.content, "utf8") > MAX_SPEC_PACKAGE_DOCUMENT_BYTES) {
		throw new Error(`Spec package document exceeds byte limit: ${id}`)
	}
	const contentHash = requireText(value.contentHash, `documents[${index}].contentHash`)
	if (hashSpecPackageContent(value.content) !== contentHash) {
		throw new Error(`Spec package document hash mismatch: ${id}`)
	}
	return {
		id,
		kind,
		title,
		fileName,
		revision: value.revision as number,
		createdAt: value.createdAt as number,
		updatedAt: value.updatedAt as number,
		content: value.content,
		contentHash,
	}
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value)
}

function requireText(value: unknown, name: string): string {
	if (typeof value !== "string" || !value.trim()) throw new Error(`Invalid .zspec ${name}`)
	return value.trim()
}

function isFiniteTimestamp(value: unknown): value is number {
	return typeof value === "number" && Number.isFinite(value) && value >= 0
}
